### ISSUE TITLE
Simplified optimisation DSL with support for EDGE

### ISSUE THREAD

**Issue by kartshy** [SODALITE-EU/application-optimisation#12]
This is for the M24 deliverable. This issue is for both adding support for AI inference in Edge and also simplifying the DSL.

**Comment by kartshy** [comment]
We are going for a simplified DSL. The previous DSL had separate sections for HPC, AI ,... and this is not sustainable
```
{
  "optimisation": {
    "enable_opt_build": true,
    "enable_autotuning":true,
    "app_type":"ai_training/hpc/big_data/ai_inference",
    "app_name":"my_app_name",
    "arch_build": {
      "cpu_type": "",
      "acc_type": ""
    },
    "app_build": {
      "version":1.0,
      "xxx": true,
      "yyy": "10.1"
    },
    "app_opt": {
      "opt1": true
      "opt2": true
    },
    "app_config": {
      "config1": "xxx",
      "config2": "xxx"
    },
    "app_data": {
      "location": "/some/data" ,
      "basedata": "Imagenet/CIFAR/MNIST" ,
      "size": 67 ,
      "count": 4389,
      "prefetch": 100,
      "cache": 100
    },
    "autotuning": {
      "tuner": "cresta",
      "input": "dsl text"
    }
  }
}
```
With
`arch-build` specifies the target architecture to build for
`app_build` specifies the dependencies of the app and version
`app_opt` specified the optimisations to be enabled
`app_config` and `app_data`
Configuration and data for the application

Other sections of the DSL has been retained. I will provide examples. But please share your thoughts.

**Comment by kartshy** [comment]
@IndikaKuma We can add a node to the model to specify the runtime optimisation refactoring model! @gioenn Do we also define entries for the Node manager (reconfiguration)

**Comment by alazzaro** [comment]
Close this issue, now outdated with the new refactoring
