### ISSUE TITLE
MODAK tests should run outside of Docker container and without MySQL

### ISSUE THREAD

**Issue by spresser-hlrs** [SODALITE-EU/application-optimisation#18]
The tests for MODAK cannot be run outside of the docker-compose environment. This makes running the tests in other contexts (eg: Jenkinsfile) difficult. At best it means these tests are integration tests and not unit tests.

Alter the tests so they can be run in standard pythonic ways as unit tests. This means they must run independently of MySQL and outside of the docker container.

**Comment by dev-zero** [comment]
@spresser-hlrs the last commit in PR #20 is a first step to address this wrt to hardcoded paths I discovered by running tests with `pytest -v tests/`

**Comment by dev-zero** [comment]
fixed by #41
