### ISSUE TITLE
Jenkins CI failures

### ISSUE THREAD

**Issue by dev-zero** [SODALITE-EU/application-optimisation#38]
I merged PR #36 but the tests are failing. Unfortunately the logs are not public.

**Comment by spresser-hlrs** [comment]
Looks like we're having name collisions between branches when not all containers are shut down correctly by the build.

```
Creating modak_modaksql_1 ... 
Creating modak_modaksql_1 ... error

ERROR: for modak_modaksql_1  Cannot start service modaksql: network modak_default is ambiguous (2 matches found on name)

ERROR: for modaksql  Cannot start service modaksql: network modak_default is ambiguous (2 matches found on name)
Encountered errors while bringing up the project.
```

I'll take a look at what's required to make more unique names.

In the meantime, I'm asking about getting @dev-zero Jenkins access as well. I remember it being a relatively trivial process.

**Comment by spresser-hlrs** [comment]
Okay, I have docker unstuck. There's no great way to remove state there. The builds are supposed to be barred from concurrently running to get into this state, but clearly that doesn't always happen.

I've got a fix for that in feat/extra_docker_reliability, which I'll put out a PR for in a moment.

I'm also seeing a test failure, which I'll open a new ticket about.

**Comment by dev-zero** [comment]
Ok, got access, fixed the remaining flake8 failures plus one I introduced.
