### ISSUE TITLE
Perfromance DSL design and integartion with IDE

### ISSUE THREAD

**Issue by kartshy** [SODALITE-EU/application-optimisation#4]
Need to come up with the full performance DSL and integrate with IDE.
The optimisation DSL workflow is shown below

![image](https://user-images.githubusercontent.com/1748577/81951333-f3a20400-95fc-11ea-9fd1-74fd6f009444.png)

Example of DSL in IDE is shown below
![image](https://user-images.githubusercontent.com/1748577/81951382-00bef300-95fd-11ea-80f6-d90b1cb6dc5d.png)

TODO: To come up with a complete list of Optimisation DSL and integrate with IDE

**Comment by jesus-gorronogoitia** [comment]
First version of Optimization DSL specification (grammar) and textual editor implemented and pushed into the IDE repository in GitHub

**Comment by jesus-gorronogoitia** [comment]
Optimization DSL specification discussion is taking place as well in #1

**Comment by jesus-gorronogoitia** [comment]
Features implemented:
- DSL for optimization and autotuning
- Textual editor for optimization models and inline autotuning models
- Syntactic model verification. Verification of model consistency according to DSL rules
- Context-aware content assistance: suggesting possible entities, providing keyword description, etc.

![OptimizationDSL1](https://user-images.githubusercontent.com/3658315/82894170-735f9500-9f52-11ea-8634-ab93d113c656.png)
![OptimizationDSL2](https://user-images.githubusercontent.com/3658315/82894181-765a8580-9f52-11ea-9313-a385de96d394.png)
![OptimizationDSL3](https://user-images.githubusercontent.com/3658315/82894183-778bb280-9f52-11ea-854c-ed7479e66c53.png)
![OptimizationDSL4](https://user-images.githubusercontent.com/3658315/82894187-79557600-9f52-11ea-8142-247f925acb2f.png)

**Comment by jesus-gorronogoitia** [comment]
New features:
- optimization DSL will be serialized in JSON and attached to the AADM as string within the optimization property, but not serialized in Turtle as a graph.
- optimization DSL needs to identify the AADM node instance (type) for which is being defined. The AADM node instance will reference the optimization model.
- Constraints will be defined as:
`constraint ( statement [AND/OR statement]*)
`
where statement is `(not)?(<property> <comparison_op> <number>)`
and comparison_op are: `>, <, >=, <=, ==, != `
- properties are those defined by the type/s in the hierarchy of the AADM instance type and in the hierarchy of those types whose capabilities satisfy the requirements of the AADM instance template type

**Comment by kartshy** [comment]
@jesus-gorronogoitia Can you please send me the DSL in json format for the hpc and ai training example, I would test it. Not urgent, but when you have time. Thanks.

**Comment by jesus-gorronogoitia** [comment]
@kartshy I need to implement the JSON serialization, and it is still not clear if the optimization model needs to be serialized in Turtle to be injected as graph into the KB, in order to permit the KB to offer recommendations. If the latter, the JSON serialization will be provided by the KB, and not by the IDE, and the availability of the JSON file will be delayed. Stay tune.

**Comment by jesus-gorronogoitia** [comment]
Implemented Optimization DSL grammar and editor support for constraints

**Comment by jesus-gorronogoitia** [comment]
Pending to associate the optimization model with associate resource types (from AADM model) in order to request the KB to properties of the hierarchy of template types for constraint properties. To be discussed with KB team

**Comment by jesus-gorronogoitia** [comment]
Remove support for constraints in optimization DSL

**Comment by jesus-gorronogoitia** [comment]
Performance Optimization model will be associated to the AADM using the keyword optimization, associated to a node_template, which references an existing optimization model by name. Then, during the save AADM model, referenced optimization models will be serialized in JSON and attached as separate files, identified by name, to the saveAADM query to the KB. Similarly, the autotunnig model (if present) will be attached as raw plain text to the query, identified by file path.

**Comment by kartshy** [comment]
For M18 deliverables, the priority is to have a working optimisation pipeline from IDE to optimiser and possible deployment to testbed.
1. IDE to support optimisation DSL + autotuning DSL
2. Reasoner to support constraints for optimisations
3. Create a JSON output for MODAK to consume 

MODAK will use the JSON DSL input and create a optimised container for deployment.
The Snow AI training example will be used for testing this workflow. 
After M18 , we can add enhancements to add intelligence in IDE and KB to infer items and help the AoE.

**Comment by kartshy** [comment]
@jesus-gorronogoitia  Can we use only small case for all entries and values in the dsl please.

**Comment by jesus-gorronogoitia** [comment]
@kartshy Do you want to use only lowercase labels for all optimization DSL entities? I can that, but there will be name collisions in few cases, particularly  with choices (options), so for those, we need to adopt new labels.
See examples below
![image](https://user-images.githubusercontent.com/3658315/84010031-5f655b80-a974-11ea-958d-24f76f2dfa6e.png)
In this case, app_type: AI_Training cannot be in lower case, otherwise it would collide with the ai_training entity below. Same for ai_framework: TensorFlow. So for options (in case you want them in lower case), the possible convention to avoid name collision is:
- Options: words separated by _, examples: ai_training, tensor_flow, etc
- Entity keywords, works joined without _, examples: aitraining, tensorflow

However this won't work with an HPC model
![image](https://user-images.githubusercontent.com/3658315/84010695-50cb7400-a975-11ea-9589-18b640f90699.png)

Proposed convention won't work here, because options: HPC, MPI, OPENCL, etc will collide with block keywords, hpc, mpi, opencl

So, that's why keeping options in UPPERCASE solve this issue, and I think it is well understood by delopers, who associate uppercase with constant labels to choose from. If you want us to use only lower case, please propose me labels for options that do no collide with block labels

**Comment by jesus-gorronogoitia** [comment]
> Remove support for constraints in optimization DSL

done

**Comment by jesus-gorronogoitia** [comment]
> Performance Optimization model will be associated to the AADM using the keyword optimization, associated to a node_template, which references an existing optimization model by name.
done

**Comment by jesus-gorronogoitia** [comment]
>  during the save AADM model, referenced optimization models will be serialized in JSON and attached as separate files, identified by name, to the saveAADM query to the KB. 
Serialized optimization models in JSON format

**Comment by kartshy** [comment]
> @kartshy Do you want to use only lowercase labels for all optimization DSL entities? I can that, but there will be name collisions in some cases, particularly with choices (options), so for those, we need to adopt new labels.
> See examples below
> ![image](https://user-images.githubusercontent.com/3658315/84010031-5f655b80-a974-11ea-958d-24f76f2dfa6e.png)
> In this case, app_type: AI_Training cannot be in lower case, otherwise it would collide with the ai_training entity below. Same for ai_framework: TensorFlow. So for options (in case you want them in lower case), a possible convention to avoid name collision could be:
> 
>     * Options: words separated by _, examples: ai_training, tensor_flow, etc
> 
>     * Entity keywords, works joined without _, examples: aitraining, tensorflow
> 
> 
> However this won't work with an HPC model
> ![image](https://user-images.githubusercontent.com/3658315/84010695-50cb7400-a975-11ea-9589-18b640f90699.png)
> 
> Proposed convention won't work here because options: HPC, MPI, OPENCL, etc will collide with block keywords, hpc, mpi, opencl
> 
> So, that's why keeping options in UPPERCASE solves this issue, and I think it is well understood by developers, who associate uppercase with constant labels to choose from. If you want us to use only lower case, please propose me labels for options that do no collide with block labels

Ok, it looks like it will not be so easy. Leave it as it is. We can discuss this after M18 when we update the DSL again.

**Comment by jesus-gorronogoitia** [comment]
> > during the save AADM model, referenced optimization models will be serialized in JSON and attached as separate files, identified by name, to the saveAADM query to the KB.
> > Serialized optimization models in JSON format

Done.

@kartshy See attached, JSON serialization for a couple of optimization models, one for AI_Training, another one for HPC

```
{
	"name": "hpc.mpi",
	"optimization": {
		"enable_opt_build": true,
		"enable_autotuning": true,
		"app_type":"HPC",
		"opt_build": {
			"cpu_type": "ARM",
			"acc_type": "NVIDIA-V100"
		},
		"autotuning": {
			"tuner": "CREATA",
			"input": "path/to/autotuning.model"
		},
		"hpc": { 
			"config":{ 
			   	"parallelisation": [ 
			   	"MPI"
			   	,"OPENACC"
			   	,"OPENCL"
			   	,"OPENMP"
			   	]
			},
			 "data":{ 
			   	"location": "/some/data" 
			   	,"basedata": "RESTART" 
			   	,"size": 67 
			   	,"count": 4389 
			}
			,"mpi": {
			       "library": "mvapch"
			       ,"version": "mvapch"
			       ,"scaling_efficiency": 0.75
			       ,"core_subscription": 1
			       ,"message_size": "small"
			}
			,"openmp": {
			   	"number_of_threads": 2
			   	,"scaling_efficiency": 1.1
			   	,"affinity": "block"
			}
			,"openacc": {
			   	"compiler": "pgi"
			   	,"version": "1.1"
			   	,"number_of_acc": 1
			}
			,"opencl": {
			   	"compiler": "cray"
			   	,"version": "cray"
			   	,"number_of_acc": 2
			}
		}
	}
}
```
```

{
	"name": "ai_training.tensor_flow",
	"optimization": {
		"enable_opt_build": true,
		"enable_autotuning": true,
		"app_type":"AI_Training",
		"opt_build": {
			"cpu_type": "ARM",
			"acc_type": "NVIDIA-V100"
		},
		"autotuning": {
			"tuner": "CREATA",
			"input": "/path/to/input/autotuning.model"
		},
		"ai_Training": {
			"config": { 
			       "ai_Framework": "TensorFlow"
			       ,"type": "translation"
			       ,"distributed_training": true
			       ,"layers": 6
			       ,"parameters": 872684236
			},
			"data": { 
				"location": "/some/data" 
				,"basedata": "Imagenet" 
				,"size": 67 
				,"count": 4389 
				,"ETL": { 
					"prefetch": 100 
					,"cache": 100
				}
			}
			,"TensorFlow": { 
				"version": "1.1" 
				,"xla": true
			}
		}
	}
}
```

**Comment by kartshy** [comment]
@jesus-gorronogoitia As discussed, I have modified the dsl to have all entries in small caps.
I am prefixing with parent node entry to avoid collision.

```
{
  "optimisation": { 
    "enable_opt_build": true, 
    "enable_autotuning":true, 
    "app_type":"ai_training/hpc/big_data/ai_inference",
    "opt_build": { 
      "cpu_type": "x86/arm/amd/power",
      "acc_type": "nvidia/amd/fpga" 
    },
    "autotuning": { 
      "tuner": "cresta",
      "input": "dsl text"
    },
    "app_type-ai_training": { 
      "config": { 
        "ai_framework": "tensorflow/pytorch/keras/cntk/mxnet",
        "type": "image_classification/object_detection/translation/recommendation/reinforncement_learning" ,
        "distributed_training": true, 
        "layers": 6 ,
        "parameters": 872684236 
      },
      "data": { 
        "location": "/some/data" ,
        "basedata": "Imagenet/CIFAR/MNIST" ,
        "size": 67 ,
        "count": 4389, 
        "etl": {
          "prefetch": 100,
          "cache": 100 
        }
      },
      "ai_framework-keras": { 
        "version": 1.1, 
        "backend": "tensorflow/pytorch/cntk/mxnet/keras"
      },
      "ai_framework-tensorflow": { 
        "version": "1.1", 
        "xla": true  
      },
      "ai_framework-pytorch": {
        "version": "1.1", 
        "glow": true
      }
    },
    "app_type-hpc": { 
      "config":{ 
          "parallelisation":"mpi/openmp/opencc/opencl" 
      },
      "data":{ 
       "location": "/some/data" ,
        "basedata": "IMAGE/RESTART" ,
        "size": 67 ,
        "count": 4389,
         "etl": { 
          "prefetch": true,
          "cache": true
        }
      },
      "parallelisation-mpi": { 
        "library": "mvapch/opnmpi", 
        "version": "1.1", 
        "scaling_efficiency": 0.75, 
        "core_subscription": 1, 
        "message_size": "small/medium/large" 
      },
      "parallelisation-openmp": {
        "number_of_threads": 2, 
        "scaling_efficiency": 0.75,
        "affinity": "block/simpe"
      },
      "parallelisation-opencc": {
        "compiler": "pgi/cray",
        "version": "1.1",
        "number_of_acc": 2
      },
      "parallelisation-opencl": {
        "compiler": "pgi/cray",
        "version": "1.1",
        "number_of_acc": 2
      }
    },
    "app_type-big_data": {},
    "app_type-ai_inference": {}
  }
}
```

**Comment by jesus-gorronogoitia** [comment]
Done, all DSL keyworks and labels in lowercase

**Comment by kartshy** [comment]
Closing this as it is supported in M18 deliverable. Will create a new issue if required.
