### ISSUE TITLE
Automate Application performance modelling

### ISSUE THREAD

**Issue by kartshy** [SODALITE-EU/application-optimisation#6]
As per D3.3 , application performance modelling should be automated

![image](https://user-images.githubusercontent.com/1748577/81951823-8d69b100-95fd-11ea-9a9e-ada693d1fc85.png)

**Comment by alazzaro** [comment]
closed via https://github.com/SODALITE-EU/application-optimisation/commit/18637ca801b67b767af55c3193e4c6615c44a174
